<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="UnityMathematics.NoDeps" Version="1.3.2" />
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IAFahim.Math.PoissonDisk\IAFahim.Math.PoissonDisk.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.Collections.NoDeps\IAFahim.Collections.NoDeps.csproj" />
  </ItemGroup>
</Project>