<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\IAFahim.Algebra.Polynomial\IAFahim.Algebra.Polynomial.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.Algebra.Sequence\IAFahim.Algebra.Sequence.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.Algebra.GraphPoly\IAFahim.Algebra.GraphPoly.csproj" />
  </ItemGroup>
</Project>
