<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\IAFahim.String.Match\IAFahim.String.Match.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.String.Palindrome\IAFahim.String.Palindrome.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.String.Compress\IAFahim.String.Compress.csproj" />
  </ItemGroup>
</Project>
