<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/IAFahim.Collections.NoDeps/IAFahim.Collections.NoDeps.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.Dsu/IAFahim.DS.Dsu.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.Fenwick/IAFahim.DS.Fenwick.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.Heap/IAFahim.DS.Heap.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.SegmentTree/IAFahim.DS.SegmentTree.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.Sparse/IAFahim.DS.Sparse.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.Grid/IAFahim.DS.Grid.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.Trie/IAFahim.DS.Trie.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.UnsafeArray/IAFahim.DS.UnsafeArray.csproj" />
    <ProjectReference Include="../../src/IAFahim.Graph.Misc/IAFahim.Graph.Misc.csproj" />
    <ProjectReference Include="../../src/IAFahim.DP/IAFahim.DP.csproj" />
    <ProjectReference Include="../../src/IAFahim.DP.General/IAFahim.DP.General.csproj" />
    <ProjectReference Include="../../src/IAFahim.DP.Knapsack/IAFahim.DP.Knapsack.csproj" />
    <ProjectReference Include="../../src/IAFahim.DP.Optimization/IAFahim.DP.Optimization.csproj" />
    <ProjectReference Include="../../src/IAFahim.Graph/IAFahim.Graph.csproj" />
    <ProjectReference Include="../../src/IAFahim.Graph.Flow/IAFahim.Graph.Flow.csproj" />
    <ProjectReference Include="../../src/IAFahim.Graph.Matching/IAFahim.Graph.Matching.csproj" />
    <ProjectReference Include="../../src/IAFahim.Graph.Tree/IAFahim.Graph.Tree.csproj" />
    <ProjectReference Include="../../src/IAFahim.Search.Bit/IAFahim.Search.Bit.csproj" />
    <ProjectReference Include="../../src/IAFahim.Permutation/IAFahim.Permutation.csproj" />
    <ProjectReference Include="../../src/IAFahim.Search.Range/IAFahim.Search.Range.csproj" />
    <ProjectReference Include="../../src/IAFahim.Search.Selection/IAFahim.Search.Selection.csproj" />
    <ProjectReference Include="../../src/IAFahim.Search.Specialized/IAFahim.Search.Specialized.csproj" />
    <ProjectReference Include="../../src/IAFahim.Search.Subset/IAFahim.Search.Subset.csproj" />
    <ProjectReference Include="../../src/IAFahim.Search.Window/IAFahim.Search.Window.csproj" />
    <ProjectReference Include="../../src/IAFahim.Sort.Insertion/IAFahim.Sort.Insertion.csproj" />
    <ProjectReference Include="../../src/IAFahim.Sort.Merge/IAFahim.Sort.Merge.csproj" />
    <ProjectReference Include="../../src/IAFahim.Sort.Partition/IAFahim.Sort.Partition.csproj" />
    <ProjectReference Include="../../src/IAFahim.Sort.Specialized/IAFahim.Sort.Specialized.csproj" />
    <ProjectReference Include="../../src/IAFahim.DS.Treap/IAFahim.DS.Treap.csproj" />
  </ItemGroup>
</Project>
