<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\IAFahim.Geometry.Hull\IAFahim.Geometry.Hull.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.Geometry.Intersect\IAFahim.Geometry.Intersect.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.Geometry.Voronoi\IAFahim.Geometry.Voronoi.csproj" />
    <ProjectReference Include="..\..\src\IAFahim.Geometry.Spatial\IAFahim.Geometry.Spatial.csproj" />
  </ItemGroup>
</Project>
